obj-m = ktcp_s.o

all:
	make -C /home/mzy/mnt/data/linux-4.9.40 M=$(PWD) modules

clean:
	make -C /home/mzy/mnt/data/linux-4.9.40 M=$(PWD) clean
#all:
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
#
#clean:
#	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
